CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS core_theme(theme_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),theme_name text UNIQUE NOT NULL,css_file text NOT NULL,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS core_user(user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text UNIQUE NOT NULL,password_hash text NOT NULL,known_name text,full_name text,user_type text NOT NULL DEFAULT 'standard_user' CHECK(user_type IN('standard_user','administration_user')),status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','active','disabled')),activation_token text UNIQUE,activation_expires_at timestamptz,activated_at timestamptz,reset_token text,reset_expires_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE core_user ADD COLUMN IF NOT EXISTS profile_photo_data_url text;
CREATE TABLE IF NOT EXISTS core_tenant(tenant_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_name text NOT NULL,tenant_type text NOT NULL CHECK(tenant_type IN('personal_tenant','public_tenant')),theme_id uuid REFERENCES core_theme(theme_id),status text NOT NULL DEFAULT 'active',created_by_user_id uuid REFERENCES core_user(user_id),updated_by_user_id uuid REFERENCES core_user(user_id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE core_tenant ADD COLUMN IF NOT EXISTS created_by_user_id uuid REFERENCES core_user(user_id);
ALTER TABLE core_tenant ADD COLUMN IF NOT EXISTS updated_by_user_id uuid REFERENCES core_user(user_id);
CREATE TABLE IF NOT EXISTS core_tenant_user(tenant_user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES core_tenant(tenant_id) ON DELETE CASCADE,email text NOT NULL,tenant_user_type text NOT NULL CHECK(tenant_user_type IN('owner','tenant_user','tenant_administrator')),status text NOT NULL DEFAULT 'active',added_by_user_id uuid REFERENCES core_user(user_id),added_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,email));
CREATE TABLE IF NOT EXISTS core_application(application_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),application_code text UNIQUE NOT NULL,application_name text NOT NULL,application_description text,application_icon_svg text,application_type text NOT NULL CHECK(application_type IN('public_application','administration_application')),route_prefix text NOT NULL,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE core_application ADD COLUMN IF NOT EXISTS application_description text;
ALTER TABLE core_application ADD COLUMN IF NOT EXISTS application_icon_svg text;
CREATE TABLE IF NOT EXISTS core_tenant_application(tenant_application_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES core_tenant(tenant_id) ON DELETE CASCADE,application_id uuid NOT NULL REFERENCES core_application(application_id) ON DELETE CASCADE,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,application_id));
CREATE TABLE IF NOT EXISTS core_tenant_application_user(tenant_application_user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_application_id uuid NOT NULL REFERENCES core_tenant_application(tenant_application_id) ON DELETE CASCADE,tenant_user_id uuid NOT NULL REFERENCES core_tenant_user(tenant_user_id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_application_id,tenant_user_id));
INSERT INTO core_theme(theme_name,css_file) VALUES
('Core Default','default.css'),
('Medical Industry','medical.css'),
('Home Industry','home.css'),
('Construction Industry','construction.css'),
('Garden Industry','garden.css'),
('Electrical Industry','electrical.css'),
('Financial Industry','financial.css'),
('Data Chef','data-chef.css')
ON CONFLICT(theme_name) DO UPDATE SET css_file=excluded.css_file,status='active',updated_at=now();
INSERT INTO core_application(application_code,application_name,application_description,application_icon_svg,application_type,route_prefix) VALUES
('core-saas','Core','Launch applications, switch tenants, and access your workspace from one central hub.','<svg viewBox="0 0 48 48" role="img" aria-label="Core"><rect class="app-icon-stroke" x="9" y="9" width="12" height="12" rx="3"/><rect class="app-icon-stroke" x="27" y="9" width="12" height="12" rx="3"/><rect class="app-icon-stroke" x="9" y="27" width="12" height="12" rx="3"/><rect class="app-icon-stroke" x="27" y="27" width="12" height="12" rx="3"/><path class="app-icon-line" d="M21 15h6M15 21v6M33 21v6M21 33h6"/></svg>','public_application','/'),
('core-admin','Core Administration','Manage platform settings, users, tenants, and application access from one secure control center.','<svg viewBox="0 0 48 48" role="img" aria-label="Core Administration"><path class="app-icon-stroke" d="M24 7l14 5v10c0 9-5.8 15.8-14 19-8.2-3.2-14-10-14-19V12l14-5z"/><path class="app-icon-line" d="M18 21h12M18 28h12M31 19v4M22 26v4"/></svg>','administration_application','/admin'),
('core-monitor','Core Monitor','Track service health, performance, and operational readiness across the platform.','<svg viewBox="0 0 48 48" role="img" aria-label="Core Monitor"><rect class="app-icon-stroke" x="8" y="10" width="32" height="22" rx="4"/><path class="app-icon-line" d="M14 24h6l3-7 5 12 3-5h3M18 39h12M24 32v7"/></svg>','administration_application','/monitor'),
('core-erp','Core ERP','Coordinate everyday business records and team notes in a simple shared workspace.','<svg viewBox="0 0 48 48" role="img" aria-label="Core ERP"><path class="app-icon-stroke" d="M13 8h18l6 6v26H13z"/><path class="app-icon-line" d="M30 8v8h7M18 22h14M18 28h14M18 34h8"/></svg>','public_application','/erp'),
('objectsphere','ObjectSphere','Organise assets, locations, and business objects into clear, connected hierarchies.','<svg viewBox="0 0 48 48" role="img" aria-label="ObjectSphere"><circle class="app-icon-stroke" cx="24" cy="12" r="5"/><circle class="app-icon-stroke" cx="14" cy="34" r="5"/><circle class="app-icon-stroke" cx="34" cy="34" r="5"/><path class="app-icon-line" d="M22 17l-6 12M26 17l6 12M19 34h10"/></svg>','public_application','/objectsphere'),
('core-tasks','Vision','Maintain your vision, turn ideas into goals, and track progress from intention to realisation.','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 42" width="42" height="42" role="img" aria-label="Vision"><g transform="translate(42 0) scale(-1 1)" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M7.2 34.2h27.6v4H7.2z"/><path d="M7.2 34.2c-2-3.8-3-7.8-3-12.2C4.2 9.8 13.9 3.2 25.4 5.8c7.1 1.6 11.9 7.7 11.9 15.3 0 4.7-1.3 9.1-3.2 13.1"/><path d="M9.4 9.3c6.8 1.6 12.4 5.9 15.7 12.1l-.9 7c-4.6 2.4-10 3.5-17 3.2"/><path d="M11.1 6.9c7.9 1.5 14.2 6.1 18.3 13.1"/><path d="M7.6 24.6c.4-4.8 2.1-8.7 5.3-11.6"/><g stroke-width="1.25"><circle cx="30.2" cy="21.9" r="2.7"/><circle cx="30.2" cy="21.9" r=".65"/></g></g></svg>','public_application','/tasks'),
('core-tools','Core Tools','Use lightweight browser tools for maps, encoding, geometry helpers, and future utility workflows.','<svg viewBox="0 0 48 48" role="img" aria-label="Core Tools"><rect class="app-icon-stroke" x="9" y="10" width="30" height="28" rx="5"/><path class="app-icon-line" d="M16 18h16M16 24h8M28 30l4 4 7-10"/></svg>','public_application','/tools')
ON CONFLICT(application_code) DO UPDATE
SET application_name=excluded.application_name,
    application_description=excluded.application_description,
    application_icon_svg=excluded.application_icon_svg,
    application_type=excluded.application_type,
    route_prefix=excluded.route_prefix,
    updated_at=now();
