-- Core ERP global reference seed data.
-- This file is intentionally visible and idempotent.
-- Tenant-specific defaults need a tenant id and are documented in ../Seed/tenant-defaults-template.sql.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS erp_currency(
  currency_code text PRIMARY KEY,
  currency_name text NOT NULL,
  decimal_places integer NOT NULL DEFAULT 2,
  is_active boolean NOT NULL DEFAULT true,
  is_seeded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS erp_country(
  country_code text PRIMARY KEY,
  country_name text NOT NULL,
  official_name text,
  alpha3_code text,
  numeric_code text,
  region text,
  subregion text,
  default_currency_code text,
  calling_code text,
  postal_code_required boolean NOT NULL DEFAULT false,
  administrative_level_label text,
  is_active boolean NOT NULL DEFAULT true,
  is_seeded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS erp_ledger_family(
  ledger_family_code text PRIMARY KEY,
  family_name text NOT NULL,
  requires_standard_account_type boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true
);

INSERT INTO erp_currency(currency_code,currency_name,decimal_places,is_seeded,is_active)
VALUES
  ('USD', 'US Dollar', 2, true),
  ('GBP', 'Pound Sterling', 2, true),
  ('EUR', 'Euro', 2, true),
  ('ZAR', 'South African Rand', 2, true)
ON CONFLICT(currency_code) DO UPDATE
SET currency_name=excluded.currency_name,
    decimal_places=excluded.decimal_places,
    is_seeded=excluded.is_seeded,
    is_active=true,
    updated_at=now();

INSERT INTO erp_country(country_code,alpha3_code,numeric_code,country_name,official_name,region,subregion,default_currency_code,calling_code,postal_code_required,administrative_level_label,is_seeded,is_active)
VALUES
  ('AF', 'AFG', '004', 'Afghanistan', 'Islamic Republic of Afghanistan', 'Asia', 'Southern Asia', 'AFN', '+93', false, 'Region', true, true),
  ('AX', 'ALA', '248', 'Åland Islands', 'Åland Islands', 'Europe', 'Northern Europe', 'EUR', '+35818', false, 'Region', true, true),
  ('AL', 'ALB', '008', 'Albania', 'Republic of Albania', 'Europe', 'Southeast Europe', 'ALL', '+355', false, 'Region', true, true),
  ('DZ', 'DZA', '012', 'Algeria', 'People''s Democratic Republic of Algeria', 'Africa', 'Northern Africa', 'DZD', '+213', true, 'Region', true, true),
  ('AS', 'ASM', '016', 'American Samoa', 'American Samoa', 'Oceania', 'Polynesia', 'USD', '+1684', false, 'Region', true, true),
  ('AD', 'AND', '020', 'Andorra', 'Principality of Andorra', 'Europe', 'Southern Europe', 'EUR', '+376', true, 'Region', true, true),
  ('AO', 'AGO', '024', 'Angola', 'Republic of Angola', 'Africa', 'Middle Africa', 'AOA', '+244', false, 'Region', true, true),
  ('AI', 'AIA', '660', 'Anguilla', 'Anguilla', 'Americas', 'Caribbean', 'XCD', '+1264', false, 'Region', true, true),
  ('AQ', 'ATA', '010', 'Antarctica', 'Antarctica', 'Antarctic', NULL, NULL, NULL, false, 'Region', true, true),
  ('AG', 'ATG', '028', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Americas', 'Caribbean', 'XCD', '+1268', false, 'Region', true, true),
  ('AR', 'ARG', '032', 'Argentina', 'Argentine Republic', 'Americas', 'South America', 'ARS', '+54', true, 'Province', true, true),
  ('AM', 'ARM', '051', 'Armenia', 'Republic of Armenia', 'Asia', 'Western Asia', 'AMD', '+374', true, 'Region', true, true),
  ('AW', 'ABW', '533', 'Aruba', 'Aruba', 'Americas', 'Caribbean', 'AWG', '+297', false, 'Region', true, true),
  ('AU', 'AUS', '036', 'Australia', 'Commonwealth of Australia', 'Oceania', 'Australia and New Zealand', 'AUD', '+61', true, 'State/Territory', true, true),
  ('AT', 'AUT', '040', 'Austria', 'Republic of Austria', 'Europe', 'Central Europe', 'EUR', '+43', true, 'State', true, true),
  ('AZ', 'AZE', '031', 'Azerbaijan', 'Republic of Azerbaijan', 'Asia', 'Western Asia', 'AZN', '+994', true, 'Region', true, true),
  ('BS', 'BHS', '044', 'Bahamas', 'Commonwealth of the Bahamas', 'Americas', 'Caribbean', 'BSD', '+1242', false, 'Region', true, true),
  ('BH', 'BHR', '048', 'Bahrain', 'Kingdom of Bahrain', 'Asia', 'Western Asia', 'BHD', '+973', true, 'Region', true, true),
  ('BD', 'BGD', '050', 'Bangladesh', 'People''s Republic of Bangladesh', 'Asia', 'Southern Asia', 'BDT', '+880', true, 'Region', true, true),
  ('BB', 'BRB', '052', 'Barbados', 'Barbados', 'Americas', 'Caribbean', 'BBD', '+1246', true, 'Region', true, true),
  ('BY', 'BLR', '112', 'Belarus', 'Republic of Belarus', 'Europe', 'Eastern Europe', 'BYN', '+375', true, 'Region', true, true),
  ('BE', 'BEL', '056', 'Belgium', 'Kingdom of Belgium', 'Europe', 'Western Europe', 'EUR', '+32', true, 'Region', true, true),
  ('BZ', 'BLZ', '084', 'Belize', 'Belize', 'Americas', 'Central America', 'BZD', '+501', false, 'Region', true, true),
  ('BJ', 'BEN', '204', 'Benin', 'Republic of Benin', 'Africa', 'Western Africa', 'XOF', '+229', false, 'Region', true, true),
  ('BM', 'BMU', '060', 'Bermuda', 'Bermuda', 'Americas', 'North America', 'BMD', '+1441', true, 'Region', true, true),
  ('BT', 'BTN', '064', 'Bhutan', 'Kingdom of Bhutan', 'Asia', 'Southern Asia', 'BTN', '+975', false, 'Region', true, true),
  ('BO', 'BOL', '068', 'Bolivia', 'Plurinational State of Bolivia', 'Americas', 'South America', 'BOB', '+591', false, 'Region', true, true),
  ('BQ', 'BES', '535', 'Caribbean Netherlands', 'Bonaire, Sint Eustatius and Saba', 'Americas', 'Caribbean', 'USD', '+599', false, 'Region', true, true),
  ('BA', 'BIH', '070', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Europe', 'Southeast Europe', 'BAM', '+387', true, 'Region', true, true),
  ('BW', 'BWA', '072', 'Botswana', 'Republic of Botswana', 'Africa', 'Southern Africa', 'BWP', '+267', false, 'Region', true, true),
  ('BV', 'BVT', '074', 'Bouvet Island', 'Bouvet Island', 'Antarctic', NULL, NULL, '+47', false, 'Region', true, true),
  ('BR', 'BRA', '076', 'Brazil', 'Federative Republic of Brazil', 'Americas', 'South America', 'BRL', '+55', true, 'State', true, true),
  ('IO', 'IOT', '086', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa', 'USD', '+246', false, 'Region', true, true),
  ('BN', 'BRN', '096', 'Brunei', 'Nation of Brunei, Abode of Peace', 'Asia', 'South-Eastern Asia', 'BND', '+673', true, 'Region', true, true),
  ('BG', 'BGR', '100', 'Bulgaria', 'Republic of Bulgaria', 'Europe', 'Southeast Europe', 'BGN', '+359', true, 'Region', true, true),
  ('BF', 'BFA', '854', 'Burkina Faso', 'Burkina Faso', 'Africa', 'Western Africa', 'XOF', '+226', false, 'Region', true, true),
  ('BI', 'BDI', '108', 'Burundi', 'Republic of Burundi', 'Africa', 'Eastern Africa', 'BIF', '+257', false, 'Region', true, true),
  ('CV', 'CPV', '132', 'Cape Verde', 'Republic of Cabo Verde', 'Africa', 'Western Africa', 'CVE', '+238', true, 'Region', true, true),
  ('KH', 'KHM', '116', 'Cambodia', 'Kingdom of Cambodia', 'Asia', 'South-Eastern Asia', 'KHR', '+855', true, 'Region', true, true),
  ('CM', 'CMR', '120', 'Cameroon', 'Republic of Cameroon', 'Africa', 'Middle Africa', 'XAF', '+237', false, 'Region', true, true),
  ('CA', 'CAN', '124', 'Canada', 'Canada', 'Americas', 'North America', 'CAD', '+1', true, 'Province/Territory', true, true),
  ('KY', 'CYM', '136', 'Cayman Islands', 'Cayman Islands', 'Americas', 'Caribbean', 'KYD', '+1345', false, 'Region', true, true),
  ('CF', 'CAF', '140', 'Central African Republic', 'Central African Republic', 'Africa', 'Middle Africa', 'XAF', '+236', false, 'Region', true, true),
  ('TD', 'TCD', '148', 'Chad', 'Republic of Chad', 'Africa', 'Middle Africa', 'XAF', '+235', false, 'Region', true, true),
  ('CL', 'CHL', '152', 'Chile', 'Republic of Chile', 'Americas', 'South America', 'CLP', '+56', true, 'Region', true, true),
  ('CN', 'CHN', '156', 'China', 'People''s Republic of China', 'Asia', 'Eastern Asia', 'CNY', '+86', true, 'Province', true, true),
  ('CX', 'CXR', '162', 'Christmas Island', 'Territory of Christmas Island', 'Oceania', 'Australia and New Zealand', 'AUD', '+61', true, 'Region', true, true),
  ('CC', 'CCK', '166', 'Cocos (Keeling) Islands', 'Territory of the Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand', 'AUD', '+61', false, 'Region', true, true),
  ('CO', 'COL', '170', 'Colombia', 'Republic of Colombia', 'Americas', 'South America', 'COP', '+57', false, 'Department', true, true),
  ('KM', 'COM', '174', 'Comoros', 'Union of the Comoros', 'Africa', 'Eastern Africa', 'KMF', '+269', false, 'Region', true, true),
  ('CD', 'COD', '180', 'DR Congo', 'Democratic Republic of the Congo', 'Africa', 'Middle Africa', 'CDF', '+243', false, 'Region', true, true),
  ('CG', 'COG', '178', 'Republic of the Congo', 'Republic of the Congo', 'Africa', 'Middle Africa', 'XAF', '+242', false, 'Region', true, true),
  ('CK', 'COK', '184', 'Cook Islands', 'Cook Islands', 'Oceania', 'Polynesia', 'CKD', '+682', false, 'Region', true, true),
  ('CR', 'CRI', '188', 'Costa Rica', 'Republic of Costa Rica', 'Americas', 'Central America', 'CRC', '+506', true, 'Region', true, true),
  ('CI', 'CIV', '384', 'Ivory Coast', 'Republic of Côte d''Ivoire', 'Africa', 'Western Africa', 'XOF', '+225', false, 'Region', true, true),
  ('HR', 'HRV', '191', 'Croatia', 'Republic of Croatia', 'Europe', 'Southeast Europe', 'HRK', '+385', true, 'Region', true, true),
  ('CU', 'CUB', '192', 'Cuba', 'Republic of Cuba', 'Americas', 'Caribbean', 'CUC', '+53', true, 'Region', true, true),
  ('CW', 'CUW', '531', 'Curaçao', 'Country of Curaçao', 'Americas', 'Caribbean', 'ANG', '+599', false, 'Region', true, true),
  ('CY', 'CYP', '196', 'Cyprus', 'Republic of Cyprus', 'Europe', 'Southern Europe', 'EUR', '+357', true, 'Region', true, true),
  ('CZ', 'CZE', '203', 'Czechia', 'Czech Republic', 'Europe', 'Central Europe', 'CZK', '+420', true, 'Region', true, true),
  ('DK', 'DNK', '208', 'Denmark', 'Kingdom of Denmark', 'Europe', 'Northern Europe', 'DKK', '+45', true, 'Region', true, true),
  ('DJ', 'DJI', '262', 'Djibouti', 'Republic of Djibouti', 'Africa', 'Eastern Africa', 'DJF', '+253', false, 'Region', true, true),
  ('DM', 'DMA', '212', 'Dominica', 'Commonwealth of Dominica', 'Americas', 'Caribbean', 'XCD', '+1767', false, 'Region', true, true),
  ('DO', 'DOM', '214', 'Dominican Republic', 'Dominican Republic', 'Americas', 'Caribbean', 'DOP', '+1', true, 'Region', true, true),
  ('EC', 'ECU', '218', 'Ecuador', 'Republic of Ecuador', 'Americas', 'South America', 'USD', '+593', true, 'Region', true, true),
  ('EG', 'EGY', '818', 'Egypt', 'Arab Republic of Egypt', 'Africa', 'Northern Africa', 'EGP', '+20', true, 'Region', true, true),
  ('SV', 'SLV', '222', 'El Salvador', 'Republic of El Salvador', 'Americas', 'Central America', 'USD', '+503', true, 'Region', true, true),
  ('GQ', 'GNQ', '226', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'Africa', 'Middle Africa', 'XAF', '+240', false, 'Region', true, true),
  ('ER', 'ERI', '232', 'Eritrea', 'State of Eritrea', 'Africa', 'Eastern Africa', 'ERN', '+291', false, 'Region', true, true),
  ('EE', 'EST', '233', 'Estonia', 'Republic of Estonia', 'Europe', 'Northern Europe', 'EUR', '+372', true, 'Region', true, true),
  ('SZ', 'SWZ', '748', 'Eswatini', 'Kingdom of Eswatini', 'Africa', 'Southern Africa', 'SZL', '+268', true, 'Region', true, true),
  ('ET', 'ETH', '231', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'Africa', 'Eastern Africa', 'ETB', '+251', true, 'Region', true, true),
  ('FK', 'FLK', '238', 'Falkland Islands', 'Falkland Islands', 'Americas', 'South America', 'FKP', '+500', false, 'Region', true, true),
  ('FO', 'FRO', '234', 'Faroe Islands', 'Faroe Islands', 'Europe', 'Northern Europe', 'DKK', '+298', true, 'Region', true, true),
  ('FJ', 'FJI', '242', 'Fiji', 'Republic of Fiji', 'Oceania', 'Melanesia', 'FJD', '+679', false, 'Region', true, true),
  ('FI', 'FIN', '246', 'Finland', 'Republic of Finland', 'Europe', 'Northern Europe', 'EUR', '+358', true, 'Region', true, true),
  ('FR', 'FRA', '250', 'France', 'French Republic', 'Europe', 'Western Europe', 'EUR', '+33', true, 'Region', true, true),
  ('GF', 'GUF', '254', 'French Guiana', 'Guiana', 'Americas', 'South America', 'EUR', '+594', true, 'Region', true, true),
  ('PF', 'PYF', '258', 'French Polynesia', 'French Polynesia', 'Oceania', 'Polynesia', 'XPF', '+689', true, 'Region', true, true),
  ('TF', 'ATF', '260', 'French Southern and Antarctic Lands', 'Territory of the French Southern and Antarctic Lands', 'Antarctic', NULL, 'EUR', '+262', false, 'Region', true, true),
  ('GA', 'GAB', '266', 'Gabon', 'Gabonese Republic', 'Africa', 'Middle Africa', 'XAF', '+241', false, 'Region', true, true),
  ('GM', 'GMB', '270', 'Gambia', 'Republic of the Gambia', 'Africa', 'Western Africa', 'GMD', '+220', false, 'Region', true, true),
  ('GE', 'GEO', '268', 'Georgia', 'Georgia', 'Asia', 'Western Asia', 'GEL', '+995', true, 'Region', true, true),
  ('DE', 'DEU', '276', 'Germany', 'Federal Republic of Germany', 'Europe', 'Western Europe', 'EUR', '+49', true, 'State', true, true),
  ('GH', 'GHA', '288', 'Ghana', 'Republic of Ghana', 'Africa', 'Western Africa', 'GHS', '+233', false, 'Region', true, true),
  ('GI', 'GIB', '292', 'Gibraltar', 'Gibraltar', 'Europe', 'Southern Europe', 'GIP', '+350', false, 'Region', true, true),
  ('GR', 'GRC', '300', 'Greece', 'Hellenic Republic', 'Europe', 'Southern Europe', 'EUR', '+30', true, 'Region', true, true),
  ('GL', 'GRL', '304', 'Greenland', 'Greenland', 'Americas', 'North America', 'DKK', '+299', true, 'Region', true, true),
  ('GD', 'GRD', '308', 'Grenada', 'Grenada', 'Americas', 'Caribbean', 'XCD', '+1473', false, 'Region', true, true),
  ('GP', 'GLP', '312', 'Guadeloupe', 'Guadeloupe', 'Americas', 'Caribbean', 'EUR', '+590', true, 'Region', true, true),
  ('GU', 'GUM', '316', 'Guam', 'Guam', 'Oceania', 'Micronesia', 'USD', '+1671', true, 'Region', true, true),
  ('GT', 'GTM', '320', 'Guatemala', 'Republic of Guatemala', 'Americas', 'Central America', 'GTQ', '+502', true, 'Region', true, true),
  ('GG', 'GGY', '831', 'Guernsey', 'Bailiwick of Guernsey', 'Europe', 'Northern Europe', 'GBP', '+44', true, 'Region', true, true),
  ('GN', 'GIN', '324', 'Guinea', 'Republic of Guinea', 'Africa', 'Western Africa', 'GNF', '+224', false, 'Region', true, true),
  ('GW', 'GNB', '624', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'Africa', 'Western Africa', 'XOF', '+245', true, 'Region', true, true),
  ('GY', 'GUY', '328', 'Guyana', 'Co-operative Republic of Guyana', 'Americas', 'South America', 'GYD', '+592', false, 'Region', true, true),
  ('HT', 'HTI', '332', 'Haiti', 'Republic of Haiti', 'Americas', 'Caribbean', 'HTG', '+509', true, 'Region', true, true),
  ('HM', 'HMD', '334', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'Antarctic', NULL, NULL, NULL, false, 'Region', true, true),
  ('VA', 'VAT', '336', 'Vatican City', 'Vatican City State', 'Europe', 'Southern Europe', 'EUR', '+3', false, 'Region', true, true),
  ('HN', 'HND', '340', 'Honduras', 'Republic of Honduras', 'Americas', 'Central America', 'HNL', '+504', true, 'Region', true, true),
  ('HK', 'HKG', '344', 'Hong Kong', 'Hong Kong Special Administrative Region of the People''s Republic of China', 'Asia', 'Eastern Asia', 'HKD', '+852', false, 'Region', true, true),
  ('HU', 'HUN', '348', 'Hungary', 'Hungary', 'Europe', 'Central Europe', 'HUF', '+36', true, 'Region', true, true),
  ('IS', 'ISL', '352', 'Iceland', 'Iceland', 'Europe', 'Northern Europe', 'ISK', '+354', true, 'Region', true, true),
  ('IN', 'IND', '356', 'India', 'Republic of India', 'Asia', 'Southern Asia', 'INR', '+91', true, 'State', true, true),
  ('ID', 'IDN', '360', 'Indonesia', 'Republic of Indonesia', 'Asia', 'South-Eastern Asia', 'IDR', '+62', true, 'Province', true, true),
  ('IR', 'IRN', '364', 'Iran', 'Islamic Republic of Iran', 'Asia', 'Southern Asia', 'IRR', '+98', true, 'Region', true, true),
  ('IQ', 'IRQ', '368', 'Iraq', 'Republic of Iraq', 'Asia', 'Western Asia', 'IQD', '+964', true, 'Region', true, true),
  ('IE', 'IRL', '372', 'Ireland', 'Republic of Ireland', 'Europe', 'Northern Europe', 'EUR', '+353', false, 'County', true, true),
  ('IM', 'IMN', '833', 'Isle of Man', 'Isle of Man', 'Europe', 'Northern Europe', 'GBP', '+44', true, 'Region', true, true),
  ('IL', 'ISR', '376', 'Israel', 'State of Israel', 'Asia', 'Western Asia', 'ILS', '+972', true, 'Region', true, true),
  ('IT', 'ITA', '380', 'Italy', 'Italian Republic', 'Europe', 'Southern Europe', 'EUR', '+39', true, 'Region', true, true),
  ('JM', 'JAM', '388', 'Jamaica', 'Jamaica', 'Americas', 'Caribbean', 'JMD', '+1876', false, 'Region', true, true),
  ('JP', 'JPN', '392', 'Japan', 'Japan', 'Asia', 'Eastern Asia', 'JPY', '+81', true, 'Prefecture', true, true),
  ('JE', 'JEY', '832', 'Jersey', 'Bailiwick of Jersey', 'Europe', 'Northern Europe', 'GBP', '+44', true, 'Region', true, true),
  ('JO', 'JOR', '400', 'Jordan', 'Hashemite Kingdom of Jordan', 'Asia', 'Western Asia', 'JOD', '+962', true, 'Region', true, true),
  ('KZ', 'KAZ', '398', 'Kazakhstan', 'Republic of Kazakhstan', 'Asia', 'Central Asia', 'KZT', '+7', true, 'Region', true, true),
  ('KE', 'KEN', '404', 'Kenya', 'Republic of Kenya', 'Africa', 'Eastern Africa', 'KES', '+254', true, 'Region', true, true),
  ('KI', 'KIR', '296', 'Kiribati', 'Independent and Sovereign Republic of Kiribati', 'Oceania', 'Micronesia', 'AUD', '+686', false, 'Region', true, true),
  ('KP', 'PRK', '408', 'North Korea', 'Democratic People''s Republic of Korea', 'Asia', 'Eastern Asia', 'KPW', '+850', true, 'Region', true, true),
  ('KR', 'KOR', '410', 'South Korea', 'Republic of Korea', 'Asia', 'Eastern Asia', 'KRW', '+82', true, 'Region', true, true),
  ('KW', 'KWT', '414', 'Kuwait', 'State of Kuwait', 'Asia', 'Western Asia', 'KWD', '+965', true, 'Region', true, true),
  ('KG', 'KGZ', '417', 'Kyrgyzstan', 'Kyrgyz Republic', 'Asia', 'Central Asia', 'KGS', '+996', true, 'Region', true, true),
  ('LA', 'LAO', '418', 'Laos', 'Lao People''s Democratic Republic', 'Asia', 'South-Eastern Asia', 'LAK', '+856', true, 'Region', true, true),
  ('LV', 'LVA', '428', 'Latvia', 'Republic of Latvia', 'Europe', 'Northern Europe', 'EUR', '+371', true, 'Region', true, true),
  ('LB', 'LBN', '422', 'Lebanon', 'Lebanese Republic', 'Asia', 'Western Asia', 'LBP', '+961', true, 'Region', true, true),
  ('LS', 'LSO', '426', 'Lesotho', 'Kingdom of Lesotho', 'Africa', 'Southern Africa', 'LSL', '+266', true, 'Region', true, true),
  ('LR', 'LBR', '430', 'Liberia', 'Republic of Liberia', 'Africa', 'Western Africa', 'LRD', '+231', true, 'Region', true, true),
  ('LY', 'LBY', '434', 'Libya', 'State of Libya', 'Africa', 'Northern Africa', 'LYD', '+218', false, 'Region', true, true),
  ('LI', 'LIE', '438', 'Liechtenstein', 'Principality of Liechtenstein', 'Europe', 'Western Europe', 'CHF', '+423', true, 'Region', true, true),
  ('LT', 'LTU', '440', 'Lithuania', 'Republic of Lithuania', 'Europe', 'Northern Europe', 'EUR', '+370', true, 'Region', true, true),
  ('LU', 'LUX', '442', 'Luxembourg', 'Grand Duchy of Luxembourg', 'Europe', 'Western Europe', 'EUR', '+352', true, 'Region', true, true),
  ('MO', 'MAC', '446', 'Macau', 'Macao Special Administrative Region of the People''s Republic of China', 'Asia', 'Eastern Asia', 'MOP', '+853', false, 'Region', true, true),
  ('MK', 'MKD', '807', 'North Macedonia', 'Republic of North Macedonia', 'Europe', 'Southeast Europe', 'MKD', '+389', true, 'Region', true, true),
  ('MG', 'MDG', '450', 'Madagascar', 'Republic of Madagascar', 'Africa', 'Eastern Africa', 'MGA', '+261', true, 'Region', true, true),
  ('MW', 'MWI', '454', 'Malawi', 'Republic of Malawi', 'Africa', 'Eastern Africa', 'MWK', '+265', false, 'Region', true, true),
  ('MY', 'MYS', '458', 'Malaysia', 'Malaysia', 'Asia', 'South-Eastern Asia', 'MYR', '+60', true, 'State', true, true),
  ('MV', 'MDV', '462', 'Maldives', 'Republic of the Maldives', 'Asia', 'Southern Asia', 'MVR', '+960', true, 'Region', true, true),
  ('ML', 'MLI', '466', 'Mali', 'Republic of Mali', 'Africa', 'Western Africa', 'XOF', '+223', false, 'Region', true, true),
  ('MT', 'MLT', '470', 'Malta', 'Republic of Malta', 'Europe', 'Southern Europe', 'EUR', '+356', true, 'Region', true, true),
  ('MH', 'MHL', '584', 'Marshall Islands', 'Republic of the Marshall Islands', 'Oceania', 'Micronesia', 'USD', '+692', false, 'Region', true, true),
  ('MQ', 'MTQ', '474', 'Martinique', 'Martinique', 'Americas', 'Caribbean', 'EUR', '+596', true, 'Region', true, true),
  ('MR', 'MRT', '478', 'Mauritania', 'Islamic Republic of Mauritania', 'Africa', 'Western Africa', 'MRU', '+222', false, 'Region', true, true),
  ('MU', 'MUS', '480', 'Mauritius', 'Republic of Mauritius', 'Africa', 'Eastern Africa', 'MUR', '+230', false, 'Region', true, true),
  ('YT', 'MYT', '175', 'Mayotte', 'Department of Mayotte', 'Africa', 'Eastern Africa', 'EUR', '+262', true, 'Region', true, true),
  ('MX', 'MEX', '484', 'Mexico', 'United Mexican States', 'Americas', 'North America', 'MXN', '+52', true, 'State', true, true),
  ('FM', 'FSM', '583', 'Micronesia', 'Federated States of Micronesia', 'Oceania', 'Micronesia', 'USD', '+691', true, 'Region', true, true),
  ('MD', 'MDA', '498', 'Moldova', 'Republic of Moldova', 'Europe', 'Eastern Europe', 'MDL', '+373', true, 'Region', true, true),
  ('MC', 'MCO', '492', 'Monaco', 'Principality of Monaco', 'Europe', 'Western Europe', 'EUR', '+377', true, 'Region', true, true),
  ('MN', 'MNG', '496', 'Mongolia', 'Mongolia', 'Asia', 'Eastern Asia', 'MNT', '+976', true, 'Region', true, true),
  ('ME', 'MNE', '499', 'Montenegro', 'Montenegro', 'Europe', 'Southeast Europe', 'EUR', '+382', true, 'Region', true, true),
  ('MS', 'MSR', '500', 'Montserrat', 'Montserrat', 'Americas', 'Caribbean', 'XCD', '+1664', false, 'Region', true, true),
  ('MA', 'MAR', '504', 'Morocco', 'Kingdom of Morocco', 'Africa', 'Northern Africa', 'MAD', '+212', true, 'Region', true, true),
  ('MZ', 'MOZ', '508', 'Mozambique', 'Republic of Mozambique', 'Africa', 'Eastern Africa', 'MZN', '+258', true, 'Region', true, true),
  ('MM', 'MMR', '104', 'Myanmar', 'Republic of the Union of Myanmar', 'Asia', 'South-Eastern Asia', 'MMK', '+95', true, 'Region', true, true),
  ('NA', 'NAM', '516', 'Namibia', 'Republic of Namibia', 'Africa', 'Southern Africa', 'NAD', '+264', false, 'Region', true, true),
  ('NR', 'NRU', '520', 'Nauru', 'Republic of Nauru', 'Oceania', 'Micronesia', 'AUD', '+674', false, 'Region', true, true),
  ('NP', 'NPL', '524', 'Nepal', 'Federal Democratic Republic of Nepal', 'Asia', 'Southern Asia', 'NPR', '+977', true, 'Region', true, true),
  ('NL', 'NLD', '528', 'Netherlands', 'Kingdom of the Netherlands', 'Europe', 'Western Europe', 'EUR', '+31', true, 'Province', true, true),
  ('NC', 'NCL', '540', 'New Caledonia', 'New Caledonia', 'Oceania', 'Melanesia', 'XPF', '+687', true, 'Region', true, true),
  ('NZ', 'NZL', '554', 'New Zealand', 'New Zealand', 'Oceania', 'Australia and New Zealand', 'NZD', '+64', true, 'Region', true, true),
  ('NI', 'NIC', '558', 'Nicaragua', 'Republic of Nicaragua', 'Americas', 'Central America', 'NIO', '+505', true, 'Region', true, true),
  ('NE', 'NER', '562', 'Niger', 'Republic of Niger', 'Africa', 'Western Africa', 'XOF', '+227', true, 'Region', true, true),
  ('NG', 'NGA', '566', 'Nigeria', 'Federal Republic of Nigeria', 'Africa', 'Western Africa', 'NGN', '+234', true, 'State', true, true),
  ('NU', 'NIU', '570', 'Niue', 'Niue', 'Oceania', 'Polynesia', 'NZD', '+683', false, 'Region', true, true),
  ('NF', 'NFK', '574', 'Norfolk Island', 'Territory of Norfolk Island', 'Oceania', 'Australia and New Zealand', 'AUD', '+672', false, 'Region', true, true),
  ('MP', 'MNP', '580', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'Oceania', 'Micronesia', 'USD', '+1670', false, 'Region', true, true),
  ('NO', 'NOR', '578', 'Norway', 'Kingdom of Norway', 'Europe', 'Northern Europe', 'NOK', '+47', true, 'Region', true, true),
  ('OM', 'OMN', '512', 'Oman', 'Sultanate of Oman', 'Asia', 'Western Asia', 'OMR', '+968', true, 'Region', true, true),
  ('PK', 'PAK', '586', 'Pakistan', 'Islamic Republic of Pakistan', 'Asia', 'Southern Asia', 'PKR', '+92', true, 'Province', true, true),
  ('PW', 'PLW', '585', 'Palau', 'Republic of Palau', 'Oceania', 'Micronesia', 'USD', '+680', true, 'Region', true, true),
  ('PS', 'PSE', '275', 'Palestine', 'State of Palestine', 'Asia', 'Western Asia', 'EGP', '+970', false, 'Region', true, true),
  ('PA', 'PAN', '591', 'Panama', 'Republic of Panama', 'Americas', 'Central America', 'PAB', '+507', false, 'Region', true, true),
  ('PG', 'PNG', '598', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'Oceania', 'Melanesia', 'PGK', '+675', true, 'Region', true, true),
  ('PY', 'PRY', '600', 'Paraguay', 'Republic of Paraguay', 'Americas', 'South America', 'PYG', '+595', true, 'Region', true, true),
  ('PE', 'PER', '604', 'Peru', 'Republic of Peru', 'Americas', 'South America', 'PEN', '+51', true, 'Region', true, true),
  ('PH', 'PHL', '608', 'Philippines', 'Republic of the Philippines', 'Asia', 'South-Eastern Asia', 'PHP', '+63', true, 'Region', true, true),
  ('PN', 'PCN', '612', 'Pitcairn Islands', 'Pitcairn Group of Islands', 'Oceania', 'Polynesia', 'NZD', '+64', false, 'Region', true, true),
  ('PL', 'POL', '616', 'Poland', 'Republic of Poland', 'Europe', 'Central Europe', 'PLN', '+48', true, 'Region', true, true),
  ('PT', 'PRT', '620', 'Portugal', 'Portuguese Republic', 'Europe', 'Southern Europe', 'EUR', '+351', true, 'District', true, true),
  ('PR', 'PRI', '630', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'Americas', 'Caribbean', 'USD', '+1', true, 'Region', true, true),
  ('QA', 'QAT', '634', 'Qatar', 'State of Qatar', 'Asia', 'Western Asia', 'QAR', '+974', false, 'Region', true, true),
  ('RE', 'REU', '638', 'Réunion', 'Réunion Island', 'Africa', 'Eastern Africa', 'EUR', '+262', true, 'Region', true, true),
  ('RO', 'ROU', '642', 'Romania', 'Romania', 'Europe', 'Southeast Europe', 'RON', '+40', true, 'Region', true, true),
  ('RU', 'RUS', '643', 'Russia', 'Russian Federation', 'Europe', 'Eastern Europe', 'RUB', '+7', true, 'Federal subject', true, true),
  ('RW', 'RWA', '646', 'Rwanda', 'Republic of Rwanda', 'Africa', 'Eastern Africa', 'RWF', '+250', false, 'Region', true, true),
  ('BL', 'BLM', '652', 'Saint Barthélemy', 'Collectivity of Saint Barthélemy', 'Americas', 'Caribbean', 'EUR', '+590', true, 'Region', true, true),
  ('SH', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', 'Western Africa', 'GBP', '+2', true, 'Region', true, true),
  ('KN', 'KNA', '659', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'Americas', 'Caribbean', 'XCD', '+1869', false, 'Region', true, true),
  ('LC', 'LCA', '662', 'Saint Lucia', 'Saint Lucia', 'Americas', 'Caribbean', 'XCD', '+1758', false, 'Region', true, true),
  ('MF', 'MAF', '663', 'Saint Martin', 'Saint Martin', 'Americas', 'Caribbean', 'EUR', '+590', true, 'Region', true, true),
  ('PM', 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'Americas', 'North America', 'EUR', '+508', true, 'Region', true, true),
  ('VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'Americas', 'Caribbean', 'XCD', '+1784', false, 'Region', true, true),
  ('WS', 'WSM', '882', 'Samoa', 'Independent State of Samoa', 'Oceania', 'Polynesia', 'WST', '+685', false, 'Region', true, true),
  ('SM', 'SMR', '674', 'San Marino', 'Republic of San Marino', 'Europe', 'Southern Europe', 'EUR', '+378', true, 'Region', true, true),
  ('ST', 'STP', '678', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'Africa', 'Middle Africa', 'STN', '+239', false, 'Region', true, true),
  ('SA', 'SAU', '682', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'Asia', 'Western Asia', 'SAR', '+966', true, 'Region', true, true),
  ('SN', 'SEN', '686', 'Senegal', 'Republic of Senegal', 'Africa', 'Western Africa', 'XOF', '+221', true, 'Region', true, true),
  ('RS', 'SRB', '688', 'Serbia', 'Republic of Serbia', 'Europe', 'Southeast Europe', 'RSD', '+381', true, 'Region', true, true),
  ('SC', 'SYC', '690', 'Seychelles', 'Republic of Seychelles', 'Africa', 'Eastern Africa', 'SCR', '+248', false, 'Region', true, true),
  ('SL', 'SLE', '694', 'Sierra Leone', 'Republic of Sierra Leone', 'Africa', 'Western Africa', 'SLL', '+232', false, 'Region', true, true),
  ('SG', 'SGP', '702', 'Singapore', 'Republic of Singapore', 'Asia', 'South-Eastern Asia', 'SGD', '+65', true, 'Region', true, true),
  ('SX', 'SXM', '534', 'Sint Maarten', 'Sint Maarten', 'Americas', 'Caribbean', 'ANG', '+1721', false, 'Region', true, true),
  ('SK', 'SVK', '703', 'Slovakia', 'Slovak Republic', 'Europe', 'Central Europe', 'EUR', '+421', true, 'Region', true, true),
  ('SI', 'SVN', '705', 'Slovenia', 'Republic of Slovenia', 'Europe', 'Central Europe', 'EUR', '+386', true, 'Region', true, true),
  ('SB', 'SLB', '090', 'Solomon Islands', 'Solomon Islands', 'Oceania', 'Melanesia', 'SBD', '+677', false, 'Region', true, true),
  ('SO', 'SOM', '706', 'Somalia', 'Federal Republic of Somalia', 'Africa', 'Eastern Africa', 'SOS', '+252', true, 'Region', true, true),
  ('ZA', 'ZAF', '710', 'South Africa', 'Republic of South Africa', 'Africa', 'Southern Africa', 'ZAR', '+27', true, 'Province', true, true),
  ('GS', 'SGS', '239', 'South Georgia', 'South Georgia and the South Sandwich Islands', 'Antarctic', NULL, 'SHP', '+500', false, 'Region', true, true),
  ('SS', 'SSD', '728', 'South Sudan', 'Republic of South Sudan', 'Africa', 'Middle Africa', 'SSP', '+211', false, 'Region', true, true),
  ('ES', 'ESP', '724', 'Spain', 'Kingdom of Spain', 'Europe', 'Southern Europe', 'EUR', '+34', true, 'Autonomous community', true, true),
  ('LK', 'LKA', '144', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'Asia', 'Southern Asia', 'LKR', '+94', true, 'Region', true, true),
  ('SD', 'SDN', '729', 'Sudan', 'Republic of the Sudan', 'Africa', 'Northern Africa', 'SDG', '+249', true, 'Region', true, true),
  ('SR', 'SUR', '740', 'Suriname', 'Republic of Suriname', 'Americas', 'South America', 'SRD', '+597', false, 'Region', true, true),
  ('SJ', 'SJM', '744', 'Svalbard and Jan Mayen', 'Svalbard og Jan Mayen', 'Europe', 'Northern Europe', 'NOK', '+4779', false, 'Region', true, true),
  ('SE', 'SWE', '752', 'Sweden', 'Kingdom of Sweden', 'Europe', 'Northern Europe', 'SEK', '+46', true, 'Region', true, true),
  ('CH', 'CHE', '756', 'Switzerland', 'Swiss Confederation', 'Europe', 'Western Europe', 'CHF', '+41', true, 'Canton', true, true),
  ('SY', 'SYR', '760', 'Syria', 'Syrian Arab Republic', 'Asia', 'Western Asia', 'SYP', '+963', false, 'Region', true, true),
  ('TW', 'TWN', '158', 'Taiwan', 'Republic of China (Taiwan)', 'Asia', 'Eastern Asia', 'TWD', '+886', true, 'Region', true, true),
  ('TJ', 'TJK', '762', 'Tajikistan', 'Republic of Tajikistan', 'Asia', 'Central Asia', 'TJS', '+992', true, 'Region', true, true),
  ('TZ', 'TZA', '834', 'Tanzania', 'United Republic of Tanzania', 'Africa', 'Eastern Africa', 'TZS', '+255', false, 'Region', true, true),
  ('TH', 'THA', '764', 'Thailand', 'Kingdom of Thailand', 'Asia', 'South-Eastern Asia', 'THB', '+66', true, 'Province', true, true),
  ('TL', 'TLS', '626', 'Timor-Leste', 'Democratic Republic of Timor-Leste', 'Asia', 'South-Eastern Asia', 'USD', '+670', false, 'Region', true, true),
  ('TG', 'TGO', '768', 'Togo', 'Togolese Republic', 'Africa', 'Western Africa', 'XOF', '+228', false, 'Region', true, true),
  ('TK', 'TKL', '772', 'Tokelau', 'Tokelau', 'Oceania', 'Polynesia', 'NZD', '+690', false, 'Region', true, true),
  ('TO', 'TON', '776', 'Tonga', 'Kingdom of Tonga', 'Oceania', 'Polynesia', 'TOP', '+676', false, 'Region', true, true),
  ('TT', 'TTO', '780', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'Americas', 'Caribbean', 'TTD', '+1868', false, 'Region', true, true),
  ('TN', 'TUN', '788', 'Tunisia', 'Tunisian Republic', 'Africa', 'Northern Africa', 'TND', '+216', true, 'Region', true, true),
  ('TR', 'TUR', '792', 'Turkey', 'Republic of Turkey', 'Asia', 'Western Asia', 'TRY', '+90', true, 'Province', true, true),
  ('TM', 'TKM', '795', 'Turkmenistan', 'Turkmenistan', 'Asia', 'Central Asia', 'TMT', '+993', true, 'Region', true, true),
  ('TC', 'TCA', '796', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'Americas', 'Caribbean', 'USD', '+1649', true, 'Region', true, true),
  ('TV', 'TUV', '798', 'Tuvalu', 'Tuvalu', 'Oceania', 'Polynesia', 'AUD', '+688', false, 'Region', true, true),
  ('UG', 'UGA', '800', 'Uganda', 'Republic of Uganda', 'Africa', 'Eastern Africa', 'UGX', '+256', false, 'Region', true, true),
  ('UA', 'UKR', '804', 'Ukraine', 'Ukraine', 'Europe', 'Eastern Europe', 'UAH', '+380', true, 'Oblast', true, true),
  ('AE', 'ARE', '784', 'United Arab Emirates', 'United Arab Emirates', 'Asia', 'Western Asia', 'AED', '+971', false, 'Region', true, true),
  ('GB', 'GBR', '826', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'Europe', 'Northern Europe', 'GBP', '+44', true, 'Country', true, true),
  ('UM', 'UMI', '581', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'Americas', 'North America', 'USD', '+268', false, 'Region', true, true),
  ('US', 'USA', '840', 'United States', 'United States of America', 'Americas', 'North America', 'USD', '+1', true, 'State', true, true),
  ('UY', 'URY', '858', 'Uruguay', 'Oriental Republic of Uruguay', 'Americas', 'South America', 'UYU', '+598', true, 'Region', true, true),
  ('UZ', 'UZB', '860', 'Uzbekistan', 'Republic of Uzbekistan', 'Asia', 'Central Asia', 'UZS', '+998', true, 'Region', true, true),
  ('VU', 'VUT', '548', 'Vanuatu', 'Republic of Vanuatu', 'Oceania', 'Melanesia', 'VUV', '+678', false, 'Region', true, true),
  ('VE', 'VEN', '862', 'Venezuela', 'Bolivarian Republic of Venezuela', 'Americas', 'South America', 'VES', '+58', true, 'Region', true, true),
  ('VN', 'VNM', '704', 'Vietnam', 'Socialist Republic of Vietnam', 'Asia', 'South-Eastern Asia', 'VND', '+84', true, 'Region', true, true),
  ('VG', 'VGB', '092', 'British Virgin Islands', 'Virgin Islands', 'Americas', 'Caribbean', 'USD', '+1284', false, 'Region', true, true),
  ('VI', 'VIR', '850', 'United States Virgin Islands', 'Virgin Islands of the United States', 'Americas', 'Caribbean', 'USD', '+1340', false, 'Region', true, true),
  ('WF', 'WLF', '876', 'Wallis and Futuna', 'Territory of the Wallis and Futuna Islands', 'Oceania', 'Polynesia', 'XPF', '+681', true, 'Region', true, true),
  ('EH', 'ESH', '732', 'Western Sahara', 'Sahrawi Arab Democratic Republic', 'Africa', 'Northern Africa', 'DZD', '+2', false, 'Region', true, true),
  ('YE', 'YEM', '887', 'Yemen', 'Republic of Yemen', 'Asia', 'Western Asia', 'YER', '+967', false, 'Region', true, true),
  ('ZM', 'ZMB', '894', 'Zambia', 'Republic of Zambia', 'Africa', 'Eastern Africa', 'ZMW', '+260', true, 'Region', true, true),
  ('ZW', 'ZWE', '716', 'Zimbabwe', 'Republic of Zimbabwe', 'Africa', 'Southern Africa', 'ZWL', '+263', false, 'Region', true, true)
ON CONFLICT(country_code) DO UPDATE
SET alpha3_code=excluded.alpha3_code,
    numeric_code=excluded.numeric_code,
    country_name=excluded.country_name,
    official_name=excluded.official_name,
    region=excluded.region,
    subregion=excluded.subregion,
    default_currency_code=excluded.default_currency_code,
    calling_code=excluded.calling_code,
    postal_code_required=excluded.postal_code_required,
    administrative_level_label=excluded.administrative_level_label,
    is_seeded=true,
    is_active=true,
    updated_at=now();

INSERT INTO erp_ledger_family(ledger_family_code,family_name,requires_standard_account_type,is_active)
VALUES
  ('gl', 'General ledger', true, true),
  ('bank', 'Bank', false, true),
  ('customer', 'Customer', false, true),
  ('vendor', 'Vendor', false, true),
  ('employee', 'Employee', false, true),
  ('project', 'Project', false, true),
  ('contract', 'Contract', false, true),
  ('loan', 'Loan', false, true)
ON CONFLICT(ledger_family_code) DO UPDATE
SET family_name=excluded.family_name,
    requires_standard_account_type=excluded.requires_standard_account_type,
    is_active=true;
